### ISSUE TITLE
issue with 'cairo' package

### ISSUE THREAD

**Issue by soumyass** [glyg/leg-joint#10]
Hi,
While running '0 - Introduction.ipynb' notebook in leg-joint module, I am getting a warning message that "RuntimeWarning: Error importing draw module, proceeding nevertheless: No module named '_cairo' ".
 Because of this warning, I am not able to access 'graph_draw' function, while running 'graph_representation.py' (error"AttributeError: 'module' object has no attribute 'graph_draw' ") . Even after I installed 'cairo' package and  using python3.4, the error still remains. Could you please suggest any solution. 

![cairo error](https://cloud.githubusercontent.com/assets/13586454/9006307/9a550f94-37a3-11e5-9643-fba7c0dc84ad.png)
![graph_draw](https://cloud.githubusercontent.com/assets/13586454/9006308/9a55669c-37a3-11e5-984b-33c073b93a65.png)

**Comment by glyg** [comment]
Hi @soumyass 

Thank you for pointing this out. I'll invesgate when I'm back. Meanwhile, you can use 

```python
plot_eptm_generic(eptm, coord1,
                               coord2,
                               ax=ax,
                               cell_kwargs=cell_kwargs,
                               edge_kwargs=edge_kwargs)
```

Where `coord1`, `coord2` are property maps. See:
https://github.com/glyg/leg-joint/blob/master/leg_joint/graph_representation.py#L363
